label: Gallery
fields:
  columns:
    type: number
    label: Columns
    default: 3
  images:
    type: list
    label: Images
    item:
      src:
        type: image
        label: Obrázek
      caption:
        type: text
        label: Popisek (Caption)
      alt:
        type: text
        label: Alternativní text (alt)
